# Generated by Django 4.2.5 on 2023-09-23 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
