# Generated by Django 4.2.5 on 2023-09-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_test_app', '0003_remove_product_accesses_user_accesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='length',
        ),
        migrations.AddField(
            model_name='lesson',
            name='length_in_seconds',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='url_adress',
            field=models.URLField(unique=True),
        ),
    ]
